source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ImageColorPicker_Example', :exclusive => true do
  pod 'ImageColorPicker', :path => '../'
end

target 'ImageColorPicker_Tests', :exclusive => true do
  pod 'ImageColorPicker', :path => '../'

  
end
